version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-ssl
    ports:
      - "${GATEWAY_PORT:-443}:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/config:/etc/letsencrypt
    networks:
      app_network:
        ipv4_address: 192.168.1.3

  ipfs-kubo:
    image: ipfs/kubo:latest
    container_name: ipfs-kubo
    volumes:
      - ./ipfs_data:/data/ipfs
      - ./001-ipfs-config.sh:/container-init.d/001-ipfs-config.sh:ro
    ports:
      - "4001:4001"
      - "4001:4001/udp"
    restart: unless-stopped
    networks:
      app_network:
        ipv4_address: 192.168.1.4

  aggregator-node:
    image: nuvoladigital/aggregator-node:latest
    container_name: aggregator-node
    entrypoint: ["/entry.sh"]
    volumes:
      - vola_data:/data
      - ./entry.sh:/entry.sh:ro
    depends_on:
      - ipfs-kubo
    environment:
      - LISTEN_ADDR=${LISTEN_ADDR:-0.0.0.0}
      - LISTEN_PORT=${LISTEN_PORT:-1331}
      - ACCOUNT=${ACCOUNT}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - SURI=${SURI}
      - CHAIN_RPC=${CHAIN_RPC}
    restart: unless-stopped
    networks:
      app_network:
        ipv4_address: 192.168.1.5

volumes:
  vola_data:
    name: aggregator_devnet_data

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
