services:
  ipfs-kubo:
    image: ipfs/kubo:latest
    container_name: ipfs-kubo
    volumes:
      - ipfs_data:/data/ipfs
      - ./001-ipfs-config.sh:/container-init.d/001-ipfs-config.sh
    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"
    restart: unless-stopped

  aggregator-node:
    image: nuvoladigital/aggregator-node:latest
    container_name: aggregator-node
    entrypoint: ["/entry.sh"]
    volumes:
      - vola_data:/data
      - ./entry.sh:/entry.sh
    depends_on:
      - ipfs-kubo
    network_mode: service:ipfs-kubo
    environment:
      - LISTEN_ADDR=${LISTEN_ADDR:-127.0.0.1}
      - LISTEN_PORT=${LISTEN_PORT:-1331}
      - ACCOUNT=${ACCOUNT}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - SURI=${SURI}
    restart: unless-stopped
volumes:
  vola_data:
    name: aggregator_testnet_data
  ipfs_data:
    name: aggregator_testnet_storage
